export const extensionIconPath: Record<string, string> = {
  // ** files
  html: "/icons/html",
  css: "/icons/css",
  js: "/icons/javascript",
  ts: "/icons/typescript",
  jsx: "/icons/react",
  tsx: "/icons/react-ts",
  gitignore: "/icons/git",
  vscode: "/icons/vscode",
  // ** folders
  node_modules: "/icons/folder-node",
  components: "/icons/folder-components",
  app: "/icons/folder-app",
  assets: "/icons/folder-assets",
  data: "/icons/folder-data",
  icons: "/icons/folder-icons",
  interfaces: "/icons/folder-interface",
  public: "/icons/folder-public",
  src: "/icons/folder-src",
  svg: "/icons/folder-svg",
  routes: "/icons/folder-routes",
};

export const extensionLanguageHighlighter: Record<string, string> = {
  arduino: "arduino",
  c: "c",
  cpp: "cpp",
  csharp: "csharp",
  css: "css",
  dart: "dart",
  dsconfig: "dsconfig",
  dtsgo: "dtsgo",
  html: "htmlbars",
  java: "java",
  js: "javascript",
  json: "json",
  kotlin: "kotlin",
  matlab: "matlab",
  php: "php",
  py: "python",
  ruby: "ruby",
  rust: "rust",
  scss: "scss",
  sql: "sql",
  swift: "swift",
  ts: "typescript",
  vhdl: "vhdl",
  xml: "xml",
};
